#!/usr/bin/env bash
#
# Branch and commit-subject conventions, checked rather than written down.
#
# Runs in CI as a step of the `Verify` job (.github/workflows/ci.yml), and locally
# with no arguments:
#
#     bash scripts/ci/check-conventions.sh
#
# Adapted from Cadence's script of the same name — see that repo if this one drifts.

set -uo pipefail

BASE="${BASE_REF:-origin/main}"
fail=0

note() { printf '  %s\n' "$*"; }
bad()  { printf '\n\033[31mFAIL\033[0m  %s\n' "$*"; fail=1; }
ok()   { printf '\033[32mok\033[0m    %s\n' "$*"; }

# ── Branch name ──────────────────────────────────────────────────────────────
# On a pull_request run the checkout is a detached merge commit, so the branch
# name is only available from the event payload.
branch="${GITHUB_HEAD_REF:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '')}"

# `claude` is not a change type -- it is the prefix a Claude Code web/worktree session
# names its own branch (e.g. claude/issue-12-investigation-uhfqzm). Accepted as-is so
# such a session never has to rename before it can push.
BRANCH_RE='^(feat|fix|docs|chore|test|ci|refactor|claude)/[a-z0-9][a-z0-9._-]*$'

if [ -z "$branch" ] || [ "$branch" = "HEAD" ]; then
	note "branch: detached HEAD and no GITHUB_HEAD_REF, nothing to check"
elif [ "$branch" = "main" ]; then
	note "branch: on main, nothing to check"
elif ! printf '%s' "$branch" | grep -qE "$BRANCH_RE"; then
	bad "branch name '$branch' does not match <type>/<slug>"
	note "type is one of: feat fix docs chore test ci refactor, or claude (a harness session's own branch)"
	note "slug is lowercase, digits, dots, dashes or underscores"
	note "lead the slug with the issue number where there is one:"
	note "    feat/12-hide-spell-levels"
	note "rename with:  git branch -m <new-name>"
else
	ok "branch name '$branch'"
fi

# ── Commit subjects ──────────────────────────────────────────────────────────
# Merges are excluded: their subject is generated by GitHub, not written by anyone.
#
# A checkout with no base -- a fresh container, a shallow clone -- used to skip
# every subject check and say so in a `note`, so it read as a pass. It is not one:
# CI has the history and will check what this run did not. So try one fetch first,
# and if that fails, say it loudly rather than in passing.
if [ "$BASE" = "origin/main" ] && ! git rev-parse --verify --quiet "$BASE" >/dev/null; then
	if [ "$(git rev-parse --is-shallow-repository 2>/dev/null)" = "true" ]; then
		git fetch --quiet --no-tags --depth=50 origin '+refs/heads/main:refs/remotes/origin/main' >/dev/null 2>&1 || true
	else
		git fetch --quiet --no-tags origin '+refs/heads/main:refs/remotes/origin/main' >/dev/null 2>&1 || true
	fi
fi

if ! git rev-parse --verify --quiet "$BASE" >/dev/null; then
	printf '\n\033[33mWARN\033[0m  %s\n' "commits: $BASE is not available and could not be fetched"
	note "subject checks did NOT run -- this is not the same result CI will get"
	note "say so in the pull request rather than reporting a clean local run"
else
	if [ "$(git rev-parse --is-shallow-repository 2>/dev/null)" = "true" ]; then
		note "commits: shallow checkout, so this range may not be every commit CI sees"
	fi

	range="$BASE..HEAD"
	count=$(git rev-list --no-merges --count "$range" 2>/dev/null || echo 0)

	if [ "$count" -eq 0 ]; then
		note "commits: none on top of $BASE"
	else
		while IFS= read -r subject; do
			[ -z "$subject" ] && continue
			len=${#subject}
			problems=()

			[ "$len" -gt 72 ] && problems+=("$len chars, over the 72 limit")
			printf '%s' "$subject" | grep -qE '\.$' && problems+=("ends with a period")
			printf '%s' "$subject" | grep -qE '^[a-z]' && problems+=("does not start with a capital")
			printf '%s' "$subject" \
				| grep -qiE '^(added|adds|fixed|fixes|updated|updates|removed|removes|changed|changes|refactored|implemented|created) ' \
				&& problems+=("not imperative -- write \"Add\", not \"Added\" or \"Adds\"")

			if [ ${#problems[@]} -eq 0 ]; then
				ok "subject \"$subject\""
			else
				bad "\"$subject\""
				for problem in "${problems[@]}"; do note "- $problem"; done
			fi
		done < <(git log --no-merges --format='%s' "$range")
	fi
fi

echo
if [ "$fail" -ne 0 ]; then
	echo "Conventions are checked here rather than written in a doc, so drift shows up"
	echo "before a PR, not after."
	exit 1
fi
echo "Conventions OK."
